-- Groundwork for linking the clan's external Discord RSVP bot (Apollo) to
-- GOCS attendance. Apollo is a third-party bot we don't control and has no
-- verified public webhook API from our side — this migration only adds what
-- GOCS needs to RECEIVE an RSVP update if the user wires one up (via
-- Apollo's own integration settings, or a small relay script watching the
-- Discord channel): a way to identify who's who, and a secret so the
-- inbound endpoint isn't wide open.

alter table public.profiles add column discord_username text;

comment on column public.profiles.discord_username is
  'Self-reported Discord username (e.g. "callsign#0" or the new-style unique username), used to match inbound RSVP webhook payloads to a profile. Optional.';

alter table public.integration_settings add column attendance_webhook_secret text;

comment on column public.integration_settings.attendance_webhook_secret is
  'Shared secret an external caller must send in the X-Webhook-Secret header to POST /api/webhooks/attendance. Generated by command staff in the UI, not by an operator.';
